service: ai-api-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 1024
  timeout: 29
  logRetentionInDays: 7

functions:
  api:
    handler: src/server.js
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
    environment:
      NODE_ENV: production
    reservedConcurrency: 100

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: 'npm'
    includeModules: true
    excludeFiles: '**/*.test.js'

  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true